log:
  filePath: "/var/log/traefik.log"
  format: json
  level: DEBUG

entryPoints:
  dns:
    address: ':53/udp'
  tcpdns:
    address: ':53'

api:
  dashboard: true
  insecure: true
providers:
  file:
    filename: "/etc/traefik/dynamic.yml"
